
name: Fuse Android Setup
description: Set up the Android environment

inputs:
  google_maps_api_key:
    description: 'Google Maps API Key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
      shell: bash
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: android
      shell: bash
    - name: Create gradle.properties
      run: |
        echo "breautek.fuse.MAPS_API_KEY=${{ inputs.google_maps_api_key }}" >> $GITHUB_WORKSPACE/android/gradle.properties
      shell: bash
    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_HOME" > $GITHUB_WORKSPACE/android/local.properties
      shell: bash
    - name: Accept Android SDK Licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
      shell: bash
