
name: Android CI

on:
  push:
    paths:
      - 'android/**'
      - 'plugins/**/android/**'
      - '.github/workflows/Android.yml'
      - '.github/actions/fuse-android-setup/action.yml'
  pull_request:
    paths:
      - 'android/**'
      - 'plugins/**/android/**'
      - '.github/workflows/Android.yml'
      - '.github/actions/fuse-android-setup/action.yml'

jobs:
  build-fuse:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: True
      - name: Set up Android environment
        uses: ./.github/actions/fuse-android-setup
        with:
          google_maps_api_key: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Build with Gradle
        run: ./build.sh android core

  build-fuse-test-tools:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: True

      - name: Set up Android environment
        uses: ./.github/actions/fuse-android-setup
        with:
          google_maps_api_key: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Build with Gradle
        run: ./build.sh android testtools

  build-native-view:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: True

      - name: Set up Android environment
        uses: ./.github/actions/fuse-android-setup
        with:
          google_maps_api_key: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Build with Gradle
        run: ./build.sh android nativeview

  build-google-maps:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: True

      - name: Set up Android environment
        uses: ./.github/actions/fuse-android-setup
        with:
          google_maps_api_key: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Build with Gradle
        run: ./build.sh android googlemaps

  build-filesystem:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: True

      - name: Set up Android environment
        uses: ./.github/actions/fuse-android-setup
        with:
          google_maps_api_key: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Build with Gradle
        run: ./build.sh android filesystem
  
  fuse-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        api-level: [30, 31, 32, 33, 34, 35]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: True

      - name: Set up Android environment
        uses: ./.github/actions/fuse-android-setup
        with:
          google_maps_api_key: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Run Tests on API ${{ matrix.api-level }}
        run: ./test.sh android core ${{ matrix.api-level }}

  filesystem-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        api-level: [30, 31, 32, 33, 34, 35]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: True

      - name: Set up Android environment
        uses: ./.github/actions/fuse-android-setup
        with:
          google_maps_api_key: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Run Tests on API ${{ matrix.api-level }}
        run: ./test.sh android filesystem ${{ matrix.api-level }}
