
name: iOS 18

on:
  push:
    paths:
      - 'ios/**'
      - '.github/workflows/ios18.yml'
  pull_request:
    paths:
      - 'ios/**'
      - '.github/workflows/ios18.yml'

jobs:
  build:
    name: Test iOS 18
    runs-on: macos-14

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: True
      - name: Install CocoaPods
        run: gem install cocoapods -v 1.15.2
      - name: Pod Install
        run: pod install --repo-update
        working-directory: ios
      - name: Build
        run: ./build.sh
        working-directory: ios
      - name: Test iOS 18.0
        run: ./test.sh "Fuse iOS 18.0" "18.0" "iPhone 15"
        working-directory: ios
