
name: iOS 17

on:
  push:
    paths:
      - 'ios/**'
      - '.github/workflows/ios17.yml'
  pull_request:
    paths:
      - 'ios/**'
      - '.github/workflows/ios17.yml'

jobs:
  build:
    name: Test iOS 17
    runs-on: macos-14

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: True
      - name: Set up iOS environment
        uses: ./.github/actions/fuse-ios-setup
        with:
          google_maps_api_key: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      - name: Test iOS 17.5
        run: ./test.sh "Fuse iOS 17.5" "17.5" "iPhone 15"
        working-directory: ios
