
name: JS Lint

on:
  push:
    paths:
      - 'js/**'
      - '.github/workflows/js-lint.yml'
  pull_request:
    paths:
      - 'js/**'
      - '.github/workflows/js-lint.yml'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [20.x, 22.x, 23.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci # For general tooling
      - run: npx turbo run lint
