
name: FuseJS

on:
  push:
    paths:
      - 'js/**'
      - '.github/workflows/js-unit-tests.yml'
  pull_request:
    paths:
      - 'js/**'
      - '.github/workflows/js-unit-tests.yml'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_versions: [20.x, 22.x, 23.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci # For general tooling
      - run: npm ci # For lib dependencies
        working-directory: js
      - run: npm run build
        working-directory: js
      - run: npm test
        working-directory: js
